/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sobczak.sptest.domain;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import static javax.persistence.CascadeType.*;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import pl.sobczak.sptest.consumerhttp.People;

/**
 *Equals and HashCode generated by NetBean
 * 
 * @author Lukasz Sobczak
 */
@Accessors(chain = true)
@Getter(AccessLevel.PACKAGE)
@Setter(AccessLevel.PACKAGE)
@NoArgsConstructor
@ToString
@Entity
class Hero {

    @Id
    Long swapiId;

    @ManyToMany(cascade = {MERGE, PERSIST})
    Set<Movie> movies;

    String name;

    Hero(People person) {
        swapiId = Long.parseLong(person.getSwapiId());
        name = person.getName();
        movies = new HashSet<>();
    }

    Hero addMovie(Movie movie) {
        movies.add(movie);
        return this;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 73 * hash + Objects.hashCode(this.swapiId);
        hash = 73 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Hero other = (Hero) obj;
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.swapiId, other.swapiId)) {
            return false;
        }
        return true;
    }

}
