name: Push Master

on:
  push:
    branches: [ master ]
  
jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
          
    #- name: Build with Maven
     # run: mvn -B package --file pom.xml
     
    - name: SonarCloud Scan
      run: mvn verify sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      after_success:
        - bash <(curl -s https://codecov.io/bash)
